### ISSUE TITLE
NoMethodError

### ISSUE THREAD

**Issue by Decipher** [invernizzi/vagrant-scp#2]
The following two errors occurred, the first with just 'vagrant scp' to see if it gave some useful information, and the second with 'vagrant scp -h':

```
/Users/stuartclark/.vagrant.d/gems/gems/vagrant-scp-0.4.0/lib/vagrant/scp/commands/scp.rb:23:in `block in execute': undefined method `include?' for nil:NilClass (NoMethodError)
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/plugin/v2/command.rb:220:in `each'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
    from /Users/stuartclark/.vagrant.d/gems/gems/vagrant-scp-0.4.0/lib/vagrant/scp/commands/scp.rb:20:in `execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/cli.rb:42:in `execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:292:in `cli'
    from /Applications/Vagrant/bin/../embedded/gems/gems/vagrant-1.6.5/bin/vagrant:174:in `<main>'
```

```
/Users/stuartclark/.vagrant.d/gems/gems/vagrant-scp-0.4.0/lib/vagrant/scp/commands/scp.rb:54:in `parse_args': undefined method `length' for nil:NilClass (NoMethodError)
    from /Users/stuartclark/.vagrant.d/gems/gems/vagrant-scp-0.4.0/lib/vagrant/scp/commands/scp.rb:13:in `execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/cli.rb:42:in `execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:292:in `cli'
    from /Applications/Vagrant/bin/../embedded/gems/gems/vagrant-1.6.5/bin/vagrant:174:in `<main>'
```

**Comment by invernizzi** [comment]
Thanks, Stuart!

**Comment by Decipher** [comment]
Np, thanks for the quick fix. Great plugin.
