### ISSUE TITLE
Incompatible with new versions of Vagrant

### ISSUE THREAD

**Issue by Protuhj** [invernizzi/vagrant-scp#46]
Since Vagrant ~~1.17~~ `2.2.17`, it seems this plugin no longer works due to vagrant updating to support ruby 3.0.

Edited to update the Vagrant version.

**Comment by liming01** [comment]
I met the same problem after vagrant version updated:

```
✗ vagrant scp --help
Traceback (most recent call last):
	4: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/bin/vagrant:231:in `<main>'
	3: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/environment.rb:290:in `cli'
	2: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/cli.rb:67:in `execute'
	1: from /Users/mingli/.vagrant.d/gems/2.7.4/gems/vagrant-scp-0.1.0/lib/vagrant/scp/commands/scp.rb:13:in `execute'
/Users/mingli/.vagrant.d/gems/2.7.4/gems/vagrant-scp-0.1.0/lib/vagrant/scp/commands/scp.rb:44:in `parse_args': undefined method `length' for nil:NilClass (NoMethodError)


✗ vagrant --version
Vagrant 2.2.18

✗ ruby --version
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
```

**Comment by h-haaks** [comment]
I'm having issues with this plugin as well.
What I noticed is that vagrant 2.2.18 installs vagrant-scp 0.1.0, but from tags here end rubygems.org version 0.5.7 should be available ...
Trying to force 0.5.7 gives
```
Installing the 'vagrant-scp --version '0.5.7'' plugin. This can take a few minutes...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

conflicting dependencies net-scp (~> 1.1) and net-scp (= 3.0.0)
  Activated net-scp-3.0.0
  which does not match conflicting dependency (~> 1.1)

  Conflicting dependency chains:
    net-scp (= 3.0.0), 3.0.0 activated

  versus:
    vagrant-scp (= 0.5.7), 0.5.7 activated, depends on
    net-scp (~> 1.1)
```

**Comment by h-haaks** [comment]
Looks like https://github.com/invernizzi/vagrant-scp/commit/6b8b15859b09d4ab89a51bd976011d20f4eb607c needs to be  released.

**Comment by ldavison** [comment]
As a work-around, you can locally build and install it. After you clone the repo, run `gem build vagrant-scp.gemspec`. Then run `vagrant plugin install /path/to/vagrant-scp-0.5.8.gem`, you should see something like this:

```
Installing the '/path/to/vagrant-scp-0.5.8.gem' plugin. This can take a few minutes...
Successfully uninstalled vagrant-scp-0.1.0
Installed the plugin 'vagrant-scp (0.5.8)'!
```

Once 0.5.8 is released, you might consider re-installing the plugin normally in order to receive future updates.

**Comment by Protuhj** [comment]
I verified that 0.5.9 gets installed when using the latest Vagrant (2.2.19).

Thank you!
